site_name: Clem Page

pages:
- Home: index.md
- Tutorial:
    - 01 - Subsection test: subsections/sub1.md

- Notes:
  - Static installer: notes/note_test.md

- axa_utils:
    - Functionalities: axa_utils/functionalities.md

theme: jekyll-theme-cayman

markdown_extensions:
  - mdx_math
  - extra
  - tables
  - fenced_code

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js
